### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#10]
setup.py.jj2 uses `command_line_interface` and `entry_point`.

coala has multiple entry points, which I modeled (too quickly?) as

```yaml
entry_points:
  console_scripts:
    - coala = coalib.coala:main
    - coala-ci = coalib.coala_ci:main
    - coala-json = coalib.coala_json:main
    - coala-format = coalib.coala_format:main
    - coala-delete-orig = coalib.coala_delete_orig:main
```

https://github.com/coala/coala/blob/master/.moban.yaml#L15

and coala-bears has

```yaml
entry_points:
  coalabears:
    - coala_official_bears = bears
```

which looks like
```py
          entry_points={
              'coalabears': [
                  'coala_official_bears = bears',
              ],
          },
```

It can also allow other types of entry points, such as
```py
    entry_points={
        'flake8.extension': [
            'flake8_putty = flake8_putty:PuttyExtension',
        ],
    },
```

impl at https://gitlab.com/coala/mobans/blob/master/templates/coala-setup.py.jj2#L129

Unless you have suggestions on how to do it better, I'll submit that as a PR, with backwards compatibility for `command_line_interface` and `entry_point` as they are a nice simple system which covers most needs.
