### ISSUE TITLE
extra_dependencies doesnt handle long lists well

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypi-mobans#18]
If I have an extra which has a long list of dependencies, they are all put onto a single line.

If the list of dependencies contains more than a single item, each item should be put onto a separate line.

**Comment by jayvdb** [comment]
for reference, the way to use it currently is like:

```yaml
extra_dependencies:
  - xls:
    - pyexcel-xls>=0.5.0
  - xlsx:
    - pyexcel-xlsx>=0.5.0
  - ods:
    - pyexcel-ods3>=0.5.0
```

https://github.com/pyexcel/pyexcel/blob/2f6c066e226019fed520af23970db3886eb36a58/pyexcel.yml#L16

The problem arises when an extra has lots of dependencies in it, like

```yaml
extra_dependencies:
  - all:
    - pyexcel-xls>=0.5.0
    - pyexcel-xlsx>=0.5.0
    - pyexcel-ods>=0.5.0
    - pyexcel-ods3>=0.5.0
```

And gets even worse when those extras also have platform environment markers.
